version: '3.9'

services:
  redis:
    container_name: redis
    image: 'redis:alpine'

  db:
    container_name: db
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  djangoapp:
    container_name: djangoapp
    build: .
    command: bash -c "python manage.py makemigrations --no-input && python manage.py migrate --noinput && python manage.py runserver -b 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  pgdata: {}
